export const toolsFa = {
  suitability: {
    title: 'آزمون تطابق‌پذیری IPL',
    description: 'با پاسخ به چند سؤال، تطابق عمومی IPL با پروفایل خود را درک کنید.',
    startLabel: 'شروع آزمون',
    nextLabel: 'بعدی',
    prevLabel: 'قبلی',
    resultLabel: 'مشاهده نتیجه',
    restartLabel: 'شروع مجدد',
    questions: [
      {
        id: 'skinTone',
        question: 'رنگ پوست خود را چگونه توصیف می‌کنید؟',
        options: [
          { label: 'بسیار روشن / پاستلی', value: 'very-light' },
          { label: 'روشن / سفید', value: 'light' },
          { label: 'متوسط / زیتونی', value: 'medium' },
          { label: 'برنزه / قهوه‌ای', value: 'tan' },
          { label: 'قهوه‌ای تیره', value: 'dark-brown' },
          { label: 'بسیار تیره', value: 'very-dark' },
        ],
      },
      {
        id: 'hairColor',
        question: 'رنگ طبیعی موی شما در ناحیه مورد نظر چیست؟',
        options: [
          { label: 'مشکی / قهوه‌ای بسیار تیره', value: 'black' },
          { label: 'قهوه‌ای تیره', value: 'dark-brown' },
          { label: 'قهوه‌ای', value: 'brown' },
          { label: 'قهوه‌ای روشن / ماه‌گرفته', value: 'light-brown' },
          { label: 'بلوند', value: 'blonde' },
          { label: 'قرمز', value: 'red' },
          { label: 'سفید / خاکستری', value: 'white' },
        ],
      },
      {
        id: 'pregnancy',
        question: 'آیا در حال حاضر باردار هستید یا در دوران شیردهی هستید؟',
        options: [
          { label: 'بله', value: 'yes' },
          { label: 'خیر', value: 'no' },
          { label: 'مطمئن نیستم / ترجیح می‌دهم نگویم', value: 'unsure' },
        ],
      },
      {
        id: 'medication',
        question: 'آیا در حال حاضر داروی حساس به نور مصرف می‌کنید (مثلاً آنتی‌بیوتیک، ایزوترتینوئین، عصاره سن‌تی‌جانز)؟',
        options: [
          { label: 'بله', value: 'yes' },
          { label: 'خیر', value: 'no' },
          { label: 'مطمئن نیستم', value: 'unsure' },
        ],
      },
      {
        id: 'skinCondition',
        question: 'آیا در ناحیه درمان بیماری پوستی فعالی دارید (مثلاً اگزما، پسوریازیس، آفتاب‌سوختگی، زخم باز)؟',
        options: [
          { label: 'بله', value: 'yes' },
          { label: 'خیر', value: 'no' },
          { label: 'مطمئن نیستم', value: 'unsure' },
        ],
      },
      {
        id: 'recentProcedure',
        question: 'آیا اخیراً عمل زیبایی در ناحیه درمان داشته‌اید (مثلاً پیل شیمیایی، لیزر، اپیلاسیون در ۲ هفته اخیر)؟',
        options: [
          { label: 'بله', value: 'yes' },
          { label: 'خیر', value: 'no' },
          { label: 'مطمئن نیستم', value: 'unsure' },
        ],
      },
    ],
    results: {
      suitable: {
        level: 'likely-suitable' as const,
        title: 'احتمالاً مناسب برای IPL',
        description: 'بر اساس پاسخ‌های شما، IPL ممکن است گزینه مناسبی باشد. این فقط راهنمایی عمومی است و جایگزین توصیه پزشکی نیست.',
        recommendations: [
          'همیشه ۲۴ تا ۴۸ ساعت قبل از درمان کامل تست پچ انجام دهید.',
          'دفترچه راهنمای رسمی مرکوری GP را کاملاً مطالعه کنید.',
          'با پایین‌ترین سطح انرژی توصیه شده شروع کنید.',
          'برنامه درمانی را منظم دنبال کنید.',
          'در صورت نگرانی با متخصص پوست مشورت کنید.',
        ],
      },
      caution: {
        level: 'caution' as const,
        title: 'با احتیاط ادامه دهید',
        description: 'برخی پاسخ‌ها عواملی را نشان می‌دهند که ممکن است بر تطابق IPL تأثیر بگذارد. لطفاً با یک متخصص مشورت کنید.',
        recommendations: [
          'قبل از استفاده از IPL با متخصص مراقبت‌های بهداشتی مشورت کنید.',
          'داروها یا شرایط خود را با پزشک discusses کنید.',
          'تست پچ کامل انجام دهید و ۴۸ ساعت صبر کنید.',
          'با پایین‌ترین تنظیمات انرژی شروع کنید.',
          'دفترچه راهنمای دستگاه را برای موارد منع مصرف بررسی کنید.',
        ],
      },
      notRecommended: {
        level: 'not-recommended' as const,
        title: 'در حال حاضر توصیه نمی‌شود',
        description: 'بر اساس پاسخ‌های شما، IPL ممکن است در حال حاضر مناسب نباشد. لطفاً با یک متخصص مشورت کنید.',
        recommendations: [
          'قبل از هرگونه درمان IPL با متخصص مراقبت‌های بهداشتی مشورت کنید.',
          'در صورت بارداری یا شیردهی از IPL استفاده نکنید.',
          'تا زمان قطع داروهای حساس به نور صبر کنید (با پزشک مشورت کنید).',
          'تا زمان بهبود کامل شرایط پوستی یا عمل‌های اخیر صبر کنید.',
          'دفترچه راهنمای مرکوری GP حاوی لیست کامل موارد منع مصرف است.',
        ],
      },
      consultProfessional: {
        level: 'consult' as const,
        title: 'با یک متخصص مشورت کنید',
        description: 'پاسخ‌های شما عدم قطعیت را نشان می‌دهد. مشورت با متقبل به شدت توصیه می‌شود.',
        recommendations: [
          'یک قرار ملاقات با متخصص پوست تنظیم کنید.',
          'دفترچه راهنمای مرکوری GP را به قرار ملاقات ببرید.',
          'سابقه پزشکی و داروهای فعلی خود را discusses کنید.',
          'تا دریافت راهنمایی حرفه‌ای درمان IPL را شروع نکنید.',
        ],
      },
    },
  },
  skinType: {
    title: 'بررسی‌کننده نوع پوست',
    description: 'دسته‌بندی‌های عمومی رنگ پوست مرتبط با IPL را بشناسید. این راهنمایی آموزشی است.',
    skinTones: [
      { id: 'fitz-1', label: 'نوع I — بسیار روشن', color: '#FDEBD0', description: 'پوست بسیار روشن. IPL ممکن است به دلیل تضاد بالا با مو تیره به خوبی کار کند.', suitability: 'تضاد بالا با مو تیره عموماً استفاده مؤثر IPL را پشتیبانی می‌کند.' },
      { id: 'fitz-2', label: 'نوع II — روشن', color: '#F5CBA7', description: 'پوست روشن. عموماً کاندیدای خوبی برای IPL با مو تیره‌تر.', suitability: 'تضاد خوب با مو تیره معمولاً اثربخشی IPL را پشتیبانی می‌کند.' },
      { id: 'fitz-3', label: 'نوع III — متوسط', color: '#E59866', description: 'رنگ پوست متوسط. IPL با تنظیمات مناسب ممکن است مناسب باشد.', suitability: 'ممکن است مناسب باشد — دستورالعمل دفترچه راهنما را دنبال کنید.' },
      { id: 'fitz-4', label: 'نوع IV — زیتونی', color: '#CA6F1E', description: 'پوست زیتونی یا قهوه‌ای روشن. اثربخشی IPL ممکن است کاهش یابد.', suitability: 'تضاد کاهش یافته ممکن است بر IPL تأثیر بگذارد.' },
      { id: 'fitz-5', label: 'نوع V — قهوه‌ای', color: '#873600', description: 'پوست قهوه‌ای. IPL ممکن است مناسب نباشد — مشورت با متخصص.', suitability: 'تضاد پایین خطر را افزایش می‌دهد. مشورت حرفه‌ای توصیه می‌شود.' },
      { id: 'fitz-6', label: 'نوع VI — تیره', color: '#4A235A', description: 'پوست قهوه‌ای تیره یا سیاه. IPL عموماً توصیه نمی‌شود.', suitability: 'IPL عموماً توصیه نمی‌شود. مشورت حرفه‌ای ضروری.' },
    ],
    note: 'مقیاس فیتزپاتریک یک سیستم طبقه‌بندی عمومی است. تطابق واقعی شما به عوامل بسیاری بستگی دارد.',
  },
  hairColor: {
    title: 'بررسی‌کننده رنگ مو',
    description: 'بفهمید رنگ مو و پیگمنتیشن چگونه ممکن است بر پاسخ IPL تأثیر بگذارد.',
    hairColors: [
      { id: 'black', label: 'مشکی', color: '#1C1C1C', response: 'محتوای بالای ملانین انرژی IPL را به طور مؤثر جذب می‌کند. عموماً پاسخ‌گوترین رنگ مو.', effectiveness: 'عموماً بیشترین پاسخ' },
      { id: 'dark-brown', label: 'قهوه‌ای تیره', color: '#3E2723', response: 'محتوای بالای ملانین جذب خوب IPL را فراهم می‌کند. معمولاً به خوبی پاسخ می‌دهد.', effectiveness: 'معمولاً پاسخ خوب' },
      { id: 'brown', label: 'قهوه‌ای', color: '#6D4C41', response: 'محتوای ملانین متوسط. ممکن است به IPL پاسخ دهد. ثبات مهم است.', effectiveness: 'ممکن است پاسخ دهد' },
      { id: 'light-brown', label: 'قهوه‌ای روشن', color: '#A1887F', response: 'محتوای ملانین پایین ممکن است اثربخشی IPL را کاهش دهد. نتایج متفاوت است.', effectiveness: 'اثربخشی کاهش یافته' },
      { id: 'blonde', label: 'بلوند', color: '#FFD54F', response: 'محتوای ملانین پایین جذب انرژی IPL را محدود می‌کند. اثربخشی ممکن است محدود باشد.', effectiveness: 'محدود' },
      { id: 'red', label: 'قرمز', color: '#E53935', response: 'موی قرمز حاوی فئوملانین است که IPL به طور مؤثر هدف نمی‌گیرد.', effectiveness: 'عموماً مؤثر نیست' },
      { id: 'white', label: 'سفید / خاکستری', color: '#E0E0E0', response: 'ملانینی برای جذب انرژی IPL وجود ندارد. IPL برای موی سفید یا خاکستری مؤثر نیست.', effectiveness: 'مؤثر نیست' },
    ],
    note: 'رنگ مو یکی از عوامل متعدد affecting نتایج IPL است. نتایج همیشه متفاوت است.',
  },
  treatmentPlanner: {
    title: 'برنامه‌ریز درمان',
    description: 'یک روتین درمانی مبتنی بر یادآوری بسازید. این جایگزین دستورالعمل دفترچه راهنما نیست.',
    areas: [
      { id: 'legs', label: 'پاها', icon: '🦵' },
      { id: 'arms', label: 'بازوها', icon: '💪' },
      { id: 'underarms', label: 'زیر بغل', icon: '✋' },
      { id: 'bikini', label: 'خط بیکینی', icon: '👗' },
      { id: 'upper-lip', label: 'بالا لب', icon: '👄' },
      { id: 'chin', label: 'چانه', icon: '🧔' },
      { id: 'full-face', label: 'صورت کامل (مردانه)', icon: '🧑' },
    ],
    frequencyOptions: [
      { label: 'هر ۱ هفته', weeks: 1 },
      { label: 'هر ۲ هفته', weeks: 2 },
      { label: 'هر ۳ هفته', weeks: 3 },
      { label: 'هر ۴ هفته', weeks: 4 },
    ],
    phases: [
      { label: 'فاز اولیه', description: 'جلسات مکررتر برای هدف‌گیری چرخه‌های فعال رشد مو', weeks: '۸–۱۲ هفته' },
      { label: 'فاز انتقال', description: 'تدریجاً تعداد جلسات را کاهش دهید', weeks: '۴–۸ هفته' },
      { label: 'فاز نگهداری', description: 'جلسات گاه‌به‌گاه برای حفظ نتایج', weeks: 'مداوم' },
    ],
    generateLabel: 'ساخت برنامه',
    disclaimer: 'این برنامه‌ریز فقط یک برنامه یادآوری عمومی ایجاد می‌کند. همیشه دفترچه راهنمای رسمی مرکوری GP را دنبال کنید.',
  },
  sessionCalculator: {
    title: 'محاسبه‌گر جلسات',
    description: 'تخمین تعداد جلسات IPL مورد نیاز بر اساس ناحیه درمان و ویژگی‌های مو.',
    stepLabels: ['انتخاب ناحیه', 'پروفایل مو', 'تخمین شما'],
    areas: [
      { id: 'legs', emoji: '🦵', label: 'پاها' },
      { id: 'arms', emoji: '💪', label: 'بازوها' },
      { id: 'underarms', emoji: '✋', label: 'زیر بغل' },
      { id: 'bikini', emoji: '👙', label: 'خط بیکینی' },
      { id: 'upper-lip', emoji: '👄', label: 'بالا لب' },
      { id: 'chin', emoji: '🧑', label: 'چانه' },
      { id: 'full-face', emoji: '🧖', label: 'صورت کامل' },
      { id: 'stomach', emoji: '🫁', label: 'شکم' },
    ],
    densityOptions: [
      { id: 'light', label: 'کم‌پشت', description: 'موهای نازک یا پراکنده' },
      { id: 'medium', label: 'متوسط', description: 'رویش متوسط' },
      { id: 'heavy', label: 'پرپشت', description: 'رویش ضخیم یا متراکم' },
    ],
    colorOptions: [
      { id: 'dark', label: 'تیره (مشکی/قهوه‌ای تیره)' },
      { id: 'brown', label: 'قهوه‌ای' },
      { id: 'blonde', label: 'بلوند' },
      { id: 'red', label: 'قرمز' },
    ],
    sensitivityOptions: [
      { id: 'low', label: 'کم' },
      { id: 'medium', label: 'متوسط' },
      { id: 'high', label: 'زیاد' },
    ],
    generateLabel: 'محاسبه تخمین',
    resultTitle: 'برنامه درمانی تخمینی شما',
    initialPhase: 'فاز درمان اولیه',
    maintenancePhase: 'فاز نگهداری',
    sessionsLabel: 'جلسه',
    weeksLabel: 'هفته',
    totalEstimated: 'مدت تخمینی کل',
    perAreaLabel: 'جزئیات هر ناحیه',
    densityNote: 'رویش پرپشت ممکن است جلسات بیشتری نیاز داشته باشد',
    colorNote: 'رنگ‌های روشن‌تر معمولاً کندتر به IPL پاسخ می‌دهند',
    restartLabel: 'شروع مجدد',
    disclaimer: 'این محاسبه‌گر صرفاً راهنمایی عمومی IPL ارائه می‌دهد. تخمین‌ها بر اساس الگوهای معمول درمان هستند و ممکن است به طور قابل توجهی متفاوت باشند. این جایگزین توصیه پزشکی یا دفترچه راهنمای رسمی نیست.',
  },
  faqAssistant: {
    title: 'دستیار سوالات متداول',
    description: 'سوالات خود را درباره مرکوری GP، فناوری IPL و شیوه‌های ایمن بپرسید.',
    placeholder: 'سوال خود را درباره مرکوری GP بپرسید...',
    placeholderFa: 'سوال خود را درباره مرکوری GP بپرسید...',
    sendLabel: 'ارسال',
    sendLabelFa: 'ارسال',
    clearLabel: 'پاک کردن چت',
    clearLabelFa: 'پاک کردن چت',
    thinkingLabel: 'در حال فکر...',
    thinkingLabelFa: 'در حال فکر...',
    errorLabel: 'خطا در دریافت پاسخ.',
    errorLabelFa: 'خطا در دریافت پاسخ.',
    suggestedQuestions: [
      'مرکوری GP چیست؟',
      'IPL چگونه کار می‌کند؟',
      'آیا IPL دائمی است؟',
      'چه رنگ‌های پوستی مناسب هستند؟',
    ],
    suggestedQuestionsFa: [
      'مرکوری GP چیست؟',
      'IPL چگونه کار می‌کند؟',
      'آیا IPL دائمی است؟',
      'چه رنگ‌های پوستی مناسب هستند؟',
    ],
  },
  progressTracker: {
    title: 'پیگیری پیشرفت',
    description: 'جلسات IPL خود را ثبت کنید و سفر درمانی خود را در طول زمان دنبال کنید.',
    welcomeTitle: 'سفر درمانی خود را دنبال کنید',
    welcomeDescription: 'هر جلسه IPL را ثبت کنید تا پیشرفت خود را مشاهده کنید. این یک ابزار ثبت شخصی است — توصیه پزشکی یا تضمینی ارائه نمی‌دهد.',
    getStartedLabel: 'ثبت اولین جلسه',
    logSessionLabel: 'ثبت جلسه جدید',
    dashboardLabel: 'مشاهده پیشرفت',
    saveLabel: 'ذخیره جلسه',
    clearDataLabel: 'پاک کردن همه داده‌ها',
    clearConfirmTitle: 'همه داده‌ها پاک شود؟',
    clearConfirmDescription: 'این کار تمام جلسات ثبت شده شما را برای همیشه حذف می‌کند. این عمل قابل بازگشت نیست.',
    cancelLabel: 'انصراف',
    confirmLabel: 'پاک کردن',
    areaLabel: 'ناحیه درمان',
    sessionNumberLabel: 'شماره جلسه',
    dateLabel: 'تاریخ',
    energyLevelLabel: 'سطح انرژی',
    comfortLevelLabel: 'سطح آسایش',
    notesLabel: 'یادداشت (اختیاری)',
    notesPlaceholder: 'حس جلسه چطور بود؟',
    areas: [
      { id: 'legs', label: 'پاها' },
      { id: 'arms', label: 'بازوها' },
      { id: 'underarms', label: 'زیر بغل' },
      { id: 'bikini', label: 'خط بیکینی' },
      { id: 'upper-lip', label: 'بالا لب' },
      { id: 'chin', label: 'چانه' },
      { id: 'full-face', label: 'صورت کامل' },
      { id: 'stomach', label: 'شکم' },
    ],
    energyLevels: ['پایین‌ترین', 'پایین', 'متوسط', 'بالا', 'بالاترین'],
    comfortLevels: ['بسیار راحت', 'راحت', 'متوسط', 'ناراحت', 'بسیار ناراحت'],
    stats: {
      totalSessions: 'کل جلسات',
      avgComfort: 'میانگین آسایش',
      commonEnergy: 'سطح انرژی رایج',
      daysSinceFirst: 'روز از اولین جلسه',
      daysSinceLast: 'روز از آخرین جلسه',
      noData: 'هنوز جلسه‌ای ثبت نشده',
    },
    sessionOf: 'جلسه {current} از تخمین {min}-{max}',
    progressLabel: 'پیشرفت',
    allAreas: 'همه نواحی',
  },
  disclaimer: {
    en: 'This tool provides general decision-support guidance only. It does not replace the official device manual, medical diagnosis, or professional medical advice.',
    fa: 'این ابزار صرفاً برای راهنمایی عمومی و تصمیم‌گیری آگاهانه طراحی شده است و جایگزین دفترچه راهنمای رسمی دستگاه، تشخیص پزشکی یا توصیه پزشک نیست.',
  },
  close: 'بستن',
  closeFa: 'بستن',
} as const;
