export const productEn = {
  title: 'Mercury GP',
  subtitle: 'Premium At-Home IPL Hair-Reduction Device',
  tagline: 'Designed for consistency, built for your routine.',
  overview: [
    'Mercury GP is an at-home IPL (Intense Pulsed Light) hair-reduction device designed to integrate into your personal care routine.',
    'Using broad-spectrum light pulses, IPL targets melanin in hair to help reduce hair growth over time with consistent use.',
    'Individual results may vary based on skin tone, hair color, treatment area, and adherence to the recommended schedule.',
  ],
  keyFeatures: [
    { icon: 'Zap', title: 'Unlimited Flashes', description: 'No cartridge replacement required. Designed for consistent flashes throughout the device lifetime.', verified: true },
    { icon: 'Plug', title: 'Corded Operation', description: 'Continuous power via corded connection. No battery charging or battery-life limitations during sessions.', verified: true },
    { icon: 'Gauge', title: 'High Flash Speed', description: 'Engineered for efficient treatment sessions, supporting a regular routine.', verified: true },
    { icon: 'Hand', title: 'Ergonomic Design', description: 'Shaped for comfortable handling during extended use.', verified: false },
    { icon: 'ShieldCheck', title: 'Built-in Safety Features', description: 'Internal safety mechanisms to support responsible at-home use.', verified: false },
    { icon: 'Headphones', title: 'Customer Support', description: 'Access to warranty details, user guide, and customer support.', verified: false },
  ],
  specifications: [
    { label: 'Technology', value: 'IPL (Intense Pulsed Light)' },
    { label: 'Power Source', value: 'Corded (mains powered)' },
    { label: 'Flash Capacity', value: 'Unlimited (no cartridge replacement)' },
    { label: 'Flash Speed', value: 'High-speed (refer to official manual for exact timing)' },
    { label: 'Treatment Areas', value: 'Body, face (refer to official manual for specific areas)' },
    { label: 'Skin Tone Range', value: 'Refer to official manual for specific guidance' },
    { label: 'Cooling System', value: 'Refer to official product specifications' },
    { label: 'Dimensions', value: 'Refer to official product specifications' },
    { label: 'Weight', value: 'Refer to official product specifications' },
    { label: 'Warranty', value: 'Refer to official warranty documentation' },
  ],
  boxContents: [
    'Mercury GP IPL Device',
    'Power Adapter',
    'User Manual',
    'Quick Start Guide',
    'Protective Storage Case',
    'Safety Goggles (refer to official packaging)',
  ],
  suitableFor: [
    'Adults seeking at-home hair reduction',
    'Individuals with light to medium skin tones',
    'Individuals with dark hair colors',
    'Those who can commit to a consistent treatment schedule',
  ],
  notSuitableFor: [
    'Children or minors',
    'Individuals with very dark skin tones',
    'Individuals with light blonde, red, white, or gray hair',
    'Pregnant or breastfeeding individuals',
    'Individuals on photosensitizing medications',
    'Those with active skin conditions in the treatment area',
  ],
  disclaimer: 'All specifications are based on available product information and should be verified with the official Mercury GP documentation. Individual results vary. This is not a medical device and does not guarantee hair removal outcomes.',
  closeLabel: 'Close',
  sectionLabels: {
    overview: 'Overview',
    keyFeatures: 'Key Features',
    specifications: 'Specifications',
    boxContents: 'What\'s in the Box',
    suitableFor: 'Suitable For',
    notSuitableFor: 'Not Suitable For',
    verified: 'Verified',
    pending: 'Pending verification',
  },
} as const;

export type ProductContent = typeof productEn;
