export const toolsEn = {
  suitability: {
    title: 'IPL Suitability Test',
    description: 'Answer a few questions to understand general IPL suitability for your profile.',
    startLabel: 'Start Test',
    nextLabel: 'Next',
    prevLabel: 'Back',
    resultLabel: 'See Result',
    restartLabel: 'Restart Test',
    questions: [
      {
        id: 'skinTone',
        question: 'How would you describe your skin tone?',
        options: [
          { label: 'Very light / porcelain', value: 'very-light' },
          { label: 'Light / fair', value: 'light' },
          { label: 'Medium / olive', value: 'medium' },
          { label: 'Tan / brown', value: 'tan' },
          { label: 'Dark brown', value: 'dark-brown' },
          { label: 'Very dark / deep', value: 'very-dark' },
        ],
      },
      {
        id: 'hairColor',
        question: 'What is your natural hair color on the area you wish to treat?',
        options: [
          { label: 'Black / very dark brown', value: 'black' },
          { label: 'Dark brown', value: 'dark-brown' },
          { label: 'Brown', value: 'brown' },
          { label: 'Light brown / auburn', value: 'light-brown' },
          { label: 'Blonde', value: 'blonde' },
          { label: 'Red / ginger', value: 'red' },
          { label: 'White / gray', value: 'white' },
        ],
      },
      {
        id: 'pregnancy',
        question: 'Are you currently pregnant or breastfeeding?',
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No', value: 'no' },
          { label: 'I\'m not sure / prefer not to answer', value: 'unsure' },
        ],
      },
      {
        id: 'medication',
        question: 'Are you currently taking any photosensitive medications (e.g., antibiotics, isotretinoin, St. John\'s Wort)?',
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No', value: 'no' },
          { label: 'I\'m not sure', value: 'unsure' },
        ],
      },
      {
        id: 'skinCondition',
        question: 'Do you have any active skin conditions on the treatment area (e.g., eczema, psoriasis, active sunburn, open wounds)?',
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No', value: 'no' },
          { label: 'I\'m not sure', value: 'unsure' },
        ],
      },
      {
        id: 'recentProcedure',
        question: 'Have you had any recent cosmetic procedures on the treatment area (e.g., chemical peel, laser, waxing in the last 2 weeks)?',
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No', value: 'no' },
          { label: 'I\'m not sure', value: 'unsure' },
        ],
      },
    ],
    results: {
      suitable: {
        level: 'likely-suitable' as const,
        title: 'Likely Suitable for IPL',
        description: 'Based on your answers, IPL may be a suitable option for you. However, this is general guidance only and does not replace professional medical advice.',
        recommendations: [
          'Always perform a patch test 24–48 hours before full treatment.',
          'Read the official Mercury GP manual thoroughly before starting.',
          'Start with the lowest recommended energy level.',
          'Follow the treatment schedule consistently.',
          'Consult a dermatologist if you have any concerns.',
        ],
      },
      caution: {
        level: 'caution' as const,
        title: 'Proceed with Caution',
        description: 'Some of your answers indicate factors that may affect IPL suitability. This does not mean IPL is unsafe for you, but you should take extra precautions and consult a professional.',
        recommendations: [
          'Consult a qualified healthcare professional or dermatologist before using IPL.',
          'Discuss any medications or conditions with your doctor.',
          'Perform a thorough patch test and wait 48 hours.',
          'If you proceed, start with the lowest energy setting.',
          'Read the official device manual carefully for contraindications.',
        ],
      },
      notRecommended: {
        level: 'not-recommended' as const,
        title: 'Not Recommended at This Time',
        description: 'Based on your answers, IPL may not be suitable for you at this time. This is general guidance — please consult a qualified healthcare professional for personalized advice.',
        recommendations: [
          'Consult a qualified healthcare professional before considering any IPL treatment.',
          'Do not use IPL devices if you are pregnant or breastfeeding.',
          'Stop using photosensitive medications before considering IPL (consult your doctor).',
          'Wait until skin conditions or recent procedures have fully healed.',
          'The official Mercury GP manual contains a full list of contraindications.',
        ],
      },
      consultProfessional: {
        level: 'consult' as const,
        title: 'Consult a Professional',
        description: 'Your answers indicate uncertainty. We strongly recommend consulting a qualified healthcare professional or dermatologist before using any IPL device.',
        recommendations: [
          'Schedule a consultation with a dermatologist or qualified professional.',
          'Bring the Mercury GP device manual to your appointment.',
          'Discuss your medical history and any current medications.',
          'Do not begin IPL treatment until you receive professional guidance.',
        ],
      },
    },
  },
  skinType: {
    title: 'Skin Tone Checker',
    description: 'Understand general skin-tone categories relevant to IPL use. This is educational guidance, not a medical assessment.',
    skinTones: [
      { id: 'fitz-1', label: 'Type I — Very Light', color: '#FDEBD0', description: 'Very fair skin, always burns, never tans. IPL may work well due to high contrast with dark hair.', suitability: 'High contrast with dark hair generally supports effective IPL use.' },
      { id: 'fitz-2', label: 'Type II — Fair', color: '#F5CBA7', description: 'Fair skin, usually burns, tans minimally. Generally good candidate for IPL with darker hair.', suitability: 'Good contrast with dark hair typically supports IPL effectiveness.' },
      { id: 'fitz-3', label: 'Type III — Medium', color: '#E59866', description: 'Medium skin tone, sometimes burns, gradually tans. IPL may be suitable with appropriate settings.', suitability: 'May be suitable — follow device manual guidelines for skin tone settings.' },
      { id: 'fitz-4', label: 'Type IV — Olive', color: '#CA6F1E', description: 'Olive or light brown skin, burns minimally, always tans. IPL effectiveness may be reduced; consult manual.', suitability: 'Reduced contrast may affect IPL effectiveness. Check device specifications.' },
      { id: 'fitz-5', label: 'Type V — Brown', color: '#873600', description: 'Brown skin, rarely burns, tans darkly. IPL may not be suitable — risk of skin damage. Consult a professional.', suitability: 'Low contrast with hair increases risk. Professional consultation strongly recommended.' },
      { id: 'fitz-6', label: 'Type VI — Dark', color: '#4A235A', description: 'Dark brown or black skin, never burns. IPL is generally not recommended due to high melanin in skin.', suitability: 'IPL generally not recommended. Professional consultation required.' },
    ],
    note: 'The Fitzpatrick scale is a general classification system. Your actual suitability depends on many factors. Always consult the official device manual and a qualified professional.',
  },
  hairColor: {
    title: 'Hair Color Checker',
    description: 'Learn how hair color and pigmentation may affect IPL response. Results vary by individual.',
    hairColors: [
      { id: 'black', label: 'Black', color: '#1C1C1C', response: 'High melanin content absorbs IPL energy effectively. Generally the most responsive hair color for IPL treatment.', effectiveness: 'Generally most responsive' },
      { id: 'dark-brown', label: 'Dark Brown', color: '#3E2723', response: 'High melanin content provides good IPL energy absorption. Typically responds well to IPL treatment.', effectiveness: 'Typically responds well' },
      { id: 'brown', label: 'Brown', color: '#6D4C41', response: 'Moderate melanin content. May respond to IPL, though results can vary. Consistency is important.', effectiveness: 'May respond, results vary' },
      { id: 'light-brown', label: 'Light Brown / Auburn', color: '#A1887F', response: 'Lower melanin content may reduce IPL effectiveness. More sessions may be needed. Results vary significantly.', effectiveness: 'Reduced effectiveness, varies' },
      { id: 'blonde', label: 'Blonde', color: '#FFD54F', response: 'Low melanin content limits IPL energy absorption. IPL may have limited effectiveness on blonde hair.', effectiveness: 'Limited effectiveness' },
      { id: 'red', label: 'Red', color: '#E53935', response: 'Red hair contains pheomelanin (not eumelanin) which IPL does not effectively target. IPL is generally not effective for red hair.', effectiveness: 'Generally not effective' },
      { id: 'white', label: 'White / Gray', color: '#E0E0E0', response: 'No melanin to absorb IPL energy. IPL is not effective on white, gray, or very light blonde hair.', effectiveness: 'Not effective' },
    ],
    note: 'Hair color is one of many factors affecting IPL results. Skin tone, treatment area, hormonal factors, and consistency also play significant roles. Individual results always vary.',
  },
  treatmentPlanner: {
    title: 'Treatment Planner',
    description: 'Build a reminder-oriented treatment routine. This does not replace the official device manual instructions.',
    areas: [
      { id: 'legs', label: 'Legs', icon: '🦵' },
      { id: 'arms', label: 'Arms', icon: '💪' },
      { id: 'underarms', label: 'Underarms', icon: '✋' },
      { id: 'bikini', label: 'Bikini Line', icon: '👗' },
      { id: 'upper-lip', label: 'Upper Lip', icon: '👄' },
      { id: 'chin', label: 'Chin', icon: '🧔' },
      { id: 'full-face', label: 'Full Face (male)', icon: '🧑' },
    ],
    frequencyOptions: [
      { label: 'Every 1 week', weeks: 1 },
      { label: 'Every 2 weeks', weeks: 2 },
      { label: 'Every 3 weeks', weeks: 3 },
      { label: 'Every 4 weeks', weeks: 4 },
    ],
    phases: [
      { label: 'Initial Phase', description: 'More frequent sessions to target active hair growth cycles', weeks: '8–12 weeks' },
      { label: 'Transition Phase', description: 'Gradually reduce frequency as hair growth slows', weeks: '4–8 weeks' },
      { label: 'Maintenance Phase', description: 'Occasional sessions to maintain results', weeks: 'Ongoing' },
    ],
    generateLabel: 'Generate Plan',
    disclaimer: 'This planner creates a general reminder schedule only. Always follow the official Mercury GP manual for treatment frequency and duration. Consult a professional for personalized guidance.',
  },
  sessionCalculator: {
    title: 'Session Calculator',
    description: 'Estimate how many IPL sessions you may need based on treatment area and hair characteristics.',
    stepLabels: ['Select Areas', 'Hair Profile', 'Your Estimate'],
    areas: [
      { id: 'legs', emoji: '🦵', label: 'Legs' },
      { id: 'arms', emoji: '💪', label: 'Arms' },
      { id: 'underarms', emoji: '✋', label: 'Underarms' },
      { id: 'bikini', emoji: '👙', label: 'Bikini Line' },
      { id: 'upper-lip', emoji: '👄', label: 'Upper Lip' },
      { id: 'chin', emoji: '🧑', label: 'Chin' },
      { id: 'full-face', emoji: '🧖', label: 'Full Face' },
      { id: 'stomach', emoji: '🫁', label: 'Stomach' },
    ],
    densityOptions: [
      { id: 'light', label: 'Light', description: 'Sparse or fine hair' },
      { id: 'medium', label: 'Medium', description: 'Average coverage' },
      { id: 'heavy', label: 'Heavy', description: 'Thick or dense hair growth' },
    ],
    colorOptions: [
      { id: 'dark', label: 'Dark (Black/Dark Brown)' },
      { id: 'brown', label: 'Brown' },
      { id: 'blonde', label: 'Blonde' },
      { id: 'red', label: 'Red' },
    ],
    sensitivityOptions: [
      { id: 'low', label: 'Low' },
      { id: 'medium', label: 'Medium' },
      { id: 'high', label: 'High' },
    ],
    generateLabel: 'Calculate Estimate',
    resultTitle: 'Your Estimated Treatment Plan',
    initialPhase: 'Initial Treatment Phase',
    maintenancePhase: 'Maintenance Phase',
    sessionsLabel: 'sessions',
    weeksLabel: 'weeks',
    totalEstimated: 'Total Estimated Timeline',
    perAreaLabel: 'Per Area Breakdown',
    densityNote: 'Heavy hair density may require additional sessions',
    colorNote: 'Lighter hair colors typically respond more slowly to IPL',
    restartLabel: 'Start Over',
    disclaimer: 'This calculator provides general IPL treatment guidance only. Estimates are based on typical treatment patterns and can vary significantly by individual. This does not replace professional medical advice or the official device manual.',
  },
  faqAssistant: {
    title: 'FAQ Assistant',
    description: 'Ask questions about Mercury GP, IPL technology, and safe usage practices.',
    placeholder: 'Ask about Mercury GP, IPL technology, skin safety...',
    placeholderFa: 'سوال خود را درباره مرکوری GP، فناوری IPL یا ایمنی بپرسید...',
    sendLabel: 'Send',
    sendLabelFa: 'ارسال',
    clearLabel: 'Clear Chat',
    clearLabelFa: 'پاک کردن چت',
    thinkingLabel: 'Thinking...',
    thinkingLabelFa: 'در حال فکر...',
    errorLabel: 'Failed to get response. Please try again.',
    errorLabelFa: 'خطا در دریافت پاسخ. لطفاً دوباره تلاش کنید.',
    suggestedQuestions: [
      'What is Mercury GP?',
      'How does IPL work?',
      'Is IPL permanent?',
      'What skin tones are suitable?',
    ],
    suggestedQuestionsFa: [
      'مرکوری GP چیست؟',
      'IPL چگونه کار می‌کند؟',
      'آیا IPL دائمی است؟',
      'چه رنگ‌های پوستی مناسب هستند؟',
    ],
  },
  progressTracker: {
    title: 'Progress Tracker',
    description: 'Log your IPL sessions and track your treatment journey over time.',
    welcomeTitle: 'Track Your Treatment Journey',
    welcomeDescription: 'Log each IPL session to visualize your progress. This is a personal tracking tool — it does not provide medical advice or guarantees.',
    getStartedLabel: 'Log Your First Session',
    logSessionLabel: 'Log New Session',
    dashboardLabel: 'View Progress',
    saveLabel: 'Save Session',
    clearDataLabel: 'Clear All Data',
    clearConfirmTitle: 'Clear All Data?',
    clearConfirmDescription: 'This will permanently delete all your logged sessions. This action cannot be undone.',
    cancelLabel: 'Cancel',
    confirmLabel: 'Clear',
    areaLabel: 'Treatment Area',
    sessionNumberLabel: 'Session Number',
    dateLabel: 'Date',
    energyLevelLabel: 'Energy Level',
    comfortLevelLabel: 'Comfort Level',
    notesLabel: 'Notes (optional)',
    notesPlaceholder: 'How did the session feel?',
    areas: [
      { id: 'legs', label: 'Legs' },
      { id: 'arms', label: 'Arms' },
      { id: 'underarms', label: 'Underarms' },
      { id: 'bikini', label: 'Bikini Line' },
      { id: 'upper-lip', label: 'Upper Lip' },
      { id: 'chin', label: 'Chin' },
      { id: 'full-face', label: 'Full Face' },
      { id: 'stomach', label: 'Stomach' },
    ],
    energyLevels: ['Lowest', 'Low', 'Medium', 'High', 'Highest'],
    comfortLevels: ['Very Comfortable', 'Comfortable', 'Moderate', 'Uncomfortable', 'Very Uncomfortable'],
    stats: {
      totalSessions: 'Total Sessions',
      avgComfort: 'Average Comfort',
      commonEnergy: 'Common Energy Level',
      daysSinceFirst: 'Days Since First Session',
      daysSinceLast: 'Days Since Last Session',
      noData: 'No sessions logged yet',
    },
    sessionOf: 'Session {current} of estimated {min}-{max}',
    progressLabel: 'Progress',
    allAreas: 'All Areas',
  },
  disclaimer: {
    en: 'This tool provides general decision-support guidance only. It does not replace the official device manual, medical diagnosis, or professional medical advice.',
    fa: 'این ابزار صرفاً برای راهنمایی عمومی و تصمیم‌گیری آگاهانه طراحی شده است و جایگزین دفترچه راهنمای رسمی دستگاه، تشخیص پزشکی یا توصیه پزشک نیست.',
  },
  close: 'Close',
  closeFa: 'بستن',
} as const;
